language: python
python:
  - "2.7"
  - "3.6"
before_install:
  # Install MongoDB for storage tests
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
install:
  - pip install -r requirements.txt
script:
  - make test
